export interface AttrDef {
  key: string;
  label: string;
  unit?: string;
  dataType: 'text' | 'number' | 'enum' | 'bool';
  filterable: boolean;
  showOnCard?: boolean;
  position: number;
}

export interface TypeDef {
  key: string;
  name: string;
  icon: string;
  position: number;
  attributes: AttrDef[];
}

export interface ComponentProduct {
  type: string;
  title: string;
  slug: string;
  price: number;
  stock: number;
  desc: string;
  attrs: Record<string, string | number>;
}

export const componentTypes: TypeDef[] = [
  {
    key: 'cpu',
    name: 'Процесори',
    icon: '🧠',
    position: 2,
    attributes: [
      { key: 'brand', label: 'Виробник', dataType: 'enum', filterable: true, position: 1 },
      { key: 'socket', label: 'Сокет', dataType: 'enum', filterable: true, showOnCard: true, position: 2 },
      {
        key: 'cores',
        label: 'Ядра',
        unit: 'ядер',
        dataType: 'number',
        filterable: true,
        showOnCard: true,
        position: 3,
      },
      { key: 'threads', label: 'Потоки', unit: 'шт', dataType: 'number', filterable: false, position: 4 },
      {
        key: 'base_clock',
        label: 'Базова частота',
        unit: 'ГГц',
        dataType: 'number',
        filterable: false,
        position: 5,
      },
      { key: 'tdp', label: 'TDP', unit: 'Вт', dataType: 'number', filterable: true, position: 6 },
    ],
  },
  {
    key: 'ram',
    name: "Оперативна пам'ять",
    icon: '🧩',
    position: 3,
    attributes: [
      { key: 'brand', label: 'Виробник', dataType: 'enum', filterable: true, position: 1 },
      {
        key: 'capacity_gb',
        label: 'Обсяг',
        unit: 'ГБ',
        dataType: 'number',
        filterable: true,
        showOnCard: true,
        position: 2,
      },
      { key: 'mem_type', label: 'Тип', dataType: 'enum', filterable: true, showOnCard: true, position: 3 },
      { key: 'speed_mhz', label: 'Частота', unit: 'МГц', dataType: 'number', filterable: true, position: 4 },
      {
        key: 'modules',
        label: 'Модулів у комплекті',
        unit: 'шт',
        dataType: 'number',
        filterable: false,
        position: 5,
      },
    ],
  },
  {
    key: 'psu',
    name: 'Блоки живлення',
    icon: '⚡',
    position: 4,
    attributes: [
      { key: 'brand', label: 'Виробник', dataType: 'enum', filterable: true, position: 1 },
      {
        key: 'wattage',
        label: 'Потужність',
        unit: 'Вт',
        dataType: 'number',
        filterable: true,
        showOnCard: true,
        position: 2,
      },
      {
        key: 'certificate',
        label: 'Сертифікат',
        dataType: 'enum',
        filterable: true,
        showOnCard: true,
        position: 3,
      },
      { key: 'modular', label: 'Модульність', dataType: 'enum', filterable: true, position: 4 },
      { key: 'form_factor', label: 'Форм-фактор', dataType: 'enum', filterable: true, position: 5 },
    ],
  },
  {
    key: 'mobo',
    name: 'Материнські плати',
    icon: '🔌',
    position: 5,
    attributes: [
      { key: 'brand', label: 'Виробник', dataType: 'enum', filterable: true, position: 1 },
      { key: 'socket', label: 'Сокет', dataType: 'enum', filterable: true, showOnCard: true, position: 2 },
      { key: 'chipset', label: 'Чипсет', dataType: 'enum', filterable: true, showOnCard: true, position: 3 },
      { key: 'form_factor', label: 'Форм-фактор', dataType: 'enum', filterable: true, position: 4 },
      { key: 'mem_type', label: "Тип пам'яті", dataType: 'enum', filterable: true, position: 5 },
      {
        key: 'mem_slots',
        label: "Слотів пам'яті",
        unit: 'шт',
        dataType: 'number',
        filterable: false,
        position: 6,
      },
      { key: 'm2_slots', label: 'Слотів M.2', unit: 'шт', dataType: 'number', filterable: true, position: 7 },
    ],
  },
  {
    key: 'case',
    name: 'Корпуси',
    icon: '🗄️',
    position: 6,
    attributes: [
      { key: 'brand', label: 'Виробник', dataType: 'enum', filterable: true, position: 1 },
      {
        key: 'form_factor',
        label: 'Форм-фактор',
        dataType: 'enum',
        filterable: true,
        showOnCard: true,
        position: 2,
      },
      {
        key: 'max_gpu_len',
        label: 'Макс. довжина відеокарти',
        unit: 'мм',
        dataType: 'number',
        filterable: true,
        showOnCard: true,
        position: 3,
      },
      {
        key: 'fans_included',
        label: 'Вентиляторів у комплекті',
        unit: 'шт',
        dataType: 'number',
        filterable: true,
        position: 4,
      },
      { key: 'side_panel', label: 'Бічна панель', dataType: 'enum', filterable: true, position: 5 },
    ],
  },
];

export const componentProducts: ComponentProduct[] = [
  {
    type: 'cpu',
    title: 'AMD Ryzen 9 9950X',
    slug: 'ryzen-9-9950x',
    price: 2799900,
    stock: 8,
    desc: '16 ядер / 32 потоки, сокет AM5. Флагман Zen 5 для роботи та ігор.',
    attrs: { brand: 'AMD', socket: 'AM5', cores: 16, threads: 32, base_clock: 4.3, tdp: 170 },
  },
  {
    type: 'cpu',
    title: 'AMD Ryzen 7 9800X3D',
    slug: 'ryzen-7-9800x3d',
    price: 2199900,
    stock: 12,
    desc: '8 ядер / 16 потоків з 3D V-Cache — найкращий ігровий процесор.',
    attrs: { brand: 'AMD', socket: 'AM5', cores: 8, threads: 16, base_clock: 4.7, tdp: 120 },
  },
  {
    type: 'cpu',
    title: 'AMD Ryzen 7 7800X3D',
    slug: 'ryzen-7-7800x3d',
    price: 1699900,
    stock: 15,
    desc: '8 ядер / 16 потоків, 3D V-Cache. Легенда ігрової продуктивності.',
    attrs: { brand: 'AMD', socket: 'AM5', cores: 8, threads: 16, base_clock: 4.2, tdp: 120 },
  },
  {
    type: 'cpu',
    title: 'AMD Ryzen 5 7600',
    slug: 'ryzen-5-7600',
    price: 849900,
    stock: 22,
    desc: '6 ядер / 12 потоків, сокет AM5. Оптимальний вибір для збірки середнього класу.',
    attrs: { brand: 'AMD', socket: 'AM5', cores: 6, threads: 12, base_clock: 3.8, tdp: 65 },
  },
  {
    type: 'cpu',
    title: 'AMD Ryzen 5 5600',
    slug: 'ryzen-5-5600',
    price: 429900,
    stock: 30,
    desc: '6 ядер / 12 потоків, сокет AM4. Бюджетна класика для ігор.',
    attrs: { brand: 'AMD', socket: 'AM4', cores: 6, threads: 12, base_clock: 3.5, tdp: 65 },
  },
  {
    type: 'cpu',
    title: 'Intel Core Ultra 9 285K',
    slug: 'core-ultra-9-285k',
    price: 2699900,
    stock: 6,
    desc: '24 ядра, сокет LGA1851. Флагман Arrow Lake з NPU.',
    attrs: { brand: 'Intel', socket: 'LGA1851', cores: 24, threads: 24, base_clock: 3.7, tdp: 125 },
  },
  {
    type: 'cpu',
    title: 'Intel Core Ultra 7 265K',
    slug: 'core-ultra-7-265k',
    price: 1699900,
    stock: 10,
    desc: '20 ядер, сокет LGA1851. Потужний процесор для роботи й ігор.',
    attrs: { brand: 'Intel', socket: 'LGA1851', cores: 20, threads: 20, base_clock: 3.9, tdp: 125 },
  },
  {
    type: 'cpu',
    title: 'Intel Core i7-14700K',
    slug: 'core-i7-14700k',
    price: 1599900,
    stock: 14,
    desc: '20 ядер / 28 потоків, сокет LGA1700. Універсальний вибір.',
    attrs: { brand: 'Intel', socket: 'LGA1700', cores: 20, threads: 28, base_clock: 3.4, tdp: 125 },
  },
  {
    type: 'cpu',
    title: 'Intel Core i5-14600K',
    slug: 'core-i5-14600k',
    price: 1099900,
    stock: 20,
    desc: '14 ядер / 20 потоків, сокет LGA1700. Відмінний ігровий процесор.',
    attrs: { brand: 'Intel', socket: 'LGA1700', cores: 14, threads: 20, base_clock: 3.5, tdp: 125 },
  },
  {
    type: 'cpu',
    title: 'Intel Core i5-13400F',
    slug: 'core-i5-13400f',
    price: 679900,
    stock: 26,
    desc: '10 ядер / 16 потоків без вбудованої графіки. Доступний і холодний.',
    attrs: { brand: 'Intel', socket: 'LGA1700', cores: 10, threads: 16, base_clock: 2.5, tdp: 65 },
  },

  {
    type: 'ram',
    title: 'Kingston Fury Beast 32GB DDR5-6000',
    slug: 'kingston-fury-beast-32-ddr5',
    price: 429900,
    stock: 25,
    desc: 'Комплект 2×16 ГБ DDR5 6000 МГц з підтримкою EXPO/XMP.',
    attrs: { brand: 'Kingston', capacity_gb: 32, mem_type: 'DDR5', speed_mhz: 6000, modules: 2 },
  },
  {
    type: 'ram',
    title: 'Kingston Fury Beast 16GB DDR4-3200',
    slug: 'kingston-fury-beast-16-ddr4',
    price: 189900,
    stock: 40,
    desc: 'Комплект 2×8 ГБ DDR4 3200 МГц. Надійна база для збірки на AM4.',
    attrs: { brand: 'Kingston', capacity_gb: 16, mem_type: 'DDR4', speed_mhz: 3200, modules: 2 },
  },
  {
    type: 'ram',
    title: 'Corsair Vengeance 32GB DDR5-6400',
    slug: 'corsair-vengeance-32-ddr5',
    price: 479900,
    stock: 18,
    desc: 'Комплект 2×16 ГБ DDR5 6400 МГц з низькими таймінгами.',
    attrs: { brand: 'Corsair', capacity_gb: 32, mem_type: 'DDR5', speed_mhz: 6400, modules: 2 },
  },
  {
    type: 'ram',
    title: 'Corsair Vengeance LPX 16GB DDR4-3600',
    slug: 'corsair-lpx-16-ddr4',
    price: 209900,
    stock: 32,
    desc: 'Комплект 2×8 ГБ DDR4 3600 МГц з низьким профілем.',
    attrs: { brand: 'Corsair', capacity_gb: 16, mem_type: 'DDR4', speed_mhz: 3600, modules: 2 },
  },
  {
    type: 'ram',
    title: 'G.Skill Trident Z5 RGB 32GB DDR5-6000',
    slug: 'gskill-trident-z5-32-ddr5',
    price: 529900,
    stock: 14,
    desc: 'Комплект 2×16 ГБ DDR5 6000 МГц з RGB-підсвіткою.',
    attrs: { brand: 'G.Skill', capacity_gb: 32, mem_type: 'DDR5', speed_mhz: 6000, modules: 2 },
  },
  {
    type: 'ram',
    title: 'G.Skill Ripjaws V 32GB DDR4-3600',
    slug: 'gskill-ripjaws-v-32-ddr4',
    price: 339900,
    stock: 20,
    desc: 'Комплект 2×16 ГБ DDR4 3600 МГц. Перевірена часом серія.',
    attrs: { brand: 'G.Skill', capacity_gb: 32, mem_type: 'DDR4', speed_mhz: 3600, modules: 2 },
  },
  {
    type: 'ram',
    title: 'Crucial Pro 64GB DDR5-5600',
    slug: 'crucial-pro-64-ddr5',
    price: 799900,
    stock: 9,
    desc: 'Комплект 2×32 ГБ DDR5 5600 МГц для робочих станцій.',
    attrs: { brand: 'Crucial', capacity_gb: 64, mem_type: 'DDR5', speed_mhz: 5600, modules: 2 },
  },
  {
    type: 'ram',
    title: 'Patriot Viper Venom 16GB DDR5-6000',
    slug: 'patriot-viper-venom-16-ddr5',
    price: 259900,
    stock: 28,
    desc: 'Комплект 2×8 ГБ DDR5 6000 МГц. Доступний вхід у DDR5.',
    attrs: { brand: 'Patriot', capacity_gb: 16, mem_type: 'DDR5', speed_mhz: 6000, modules: 2 },
  },

  {
    type: 'psu',
    title: 'Corsair RM850e',
    slug: 'corsair-rm850e',
    price: 499900,
    stock: 20,
    desc: '850 Вт, 80 PLUS Gold, повністю модульний. Роз’єм 12VHPWR для нових GPU.',
    attrs: {
      brand: 'Corsair',
      wattage: 850,
      certificate: '80 PLUS Gold',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'Corsair RM1000x',
    slug: 'corsair-rm1000x',
    price: 749900,
    stock: 12,
    desc: '1000 Вт, 80 PLUS Gold, тихий вентилятор 135 мм.',
    attrs: {
      brand: 'Corsair',
      wattage: 1000,
      certificate: '80 PLUS Gold',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'be quiet! Pure Power 12 M 750W',
    slug: 'bequiet-pure-power-12m-750',
    price: 429900,
    stock: 16,
    desc: '750 Вт, 80 PLUS Gold, майже безшумна робота.',
    attrs: {
      brand: 'be quiet!',
      wattage: 750,
      certificate: '80 PLUS Gold',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'Seasonic Focus GX-650',
    slug: 'seasonic-focus-gx-650',
    price: 399900,
    stock: 18,
    desc: '650 Вт, 80 PLUS Gold, 10 років гарантії.',
    attrs: {
      brand: 'Seasonic',
      wattage: 650,
      certificate: '80 PLUS Gold',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'Seasonic Prime TX-1000',
    slug: 'seasonic-prime-tx-1000',
    price: 1299900,
    stock: 5,
    desc: '1000 Вт, 80 PLUS Titanium — найвища ефективність на ринку.',
    attrs: {
      brand: 'Seasonic',
      wattage: 1000,
      certificate: '80 PLUS Titanium',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'Cooler Master MWE Bronze 600',
    slug: 'cm-mwe-bronze-600',
    price: 189900,
    stock: 30,
    desc: '600 Вт, 80 PLUS Bronze. Надійний бюджетний варіант.',
    attrs: {
      brand: 'Cooler Master',
      wattage: 600,
      certificate: '80 PLUS Bronze',
      modular: 'Немодульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'Deepcool PK550D',
    slug: 'deepcool-pk550d',
    price: 149900,
    stock: 34,
    desc: '550 Вт, 80 PLUS Bronze. Для офісних і базових ігрових збірок.',
    attrs: {
      brand: 'Deepcool',
      wattage: 550,
      certificate: '80 PLUS Bronze',
      modular: 'Немодульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'ASUS ROG Loki SFX-L 850W',
    slug: 'asus-rog-loki-sfx-850',
    price: 899900,
    stock: 7,
    desc: '850 Вт, 80 PLUS Platinum, форм-фактор SFX-L для компактних збірок.',
    attrs: {
      brand: 'ASUS',
      wattage: 850,
      certificate: '80 PLUS Platinum',
      modular: 'Повністю модульний',
      form_factor: 'SFX',
    },
  },
  {
    type: 'psu',
    title: 'MSI MAG A750GL',
    slug: 'msi-mag-a750gl',
    price: 359900,
    stock: 22,
    desc: '750 Вт, 80 PLUS Gold, кабель 12VHPWR у комплекті.',
    attrs: {
      brand: 'MSI',
      wattage: 750,
      certificate: '80 PLUS Gold',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },
  {
    type: 'psu',
    title: 'Chieftec Polaris 1050W',
    slug: 'chieftec-polaris-1050',
    price: 699900,
    stock: 10,
    desc: '1050 Вт, 80 PLUS Platinum. Запас потужності для топових GPU.',
    attrs: {
      brand: 'Chieftec',
      wattage: 1050,
      certificate: '80 PLUS Platinum',
      modular: 'Повністю модульний',
      form_factor: 'ATX',
    },
  },

  {
    type: 'mobo',
    title: 'ASUS ROG Strix X870E-E Gaming',
    slug: 'asus-x870e-e',
    price: 1899900,
    stock: 7,
    desc: 'Флагманська плата на AM5 з чипсетом X870E: PCIe 5.0, Wi-Fi 7, 4 слоти M.2.',
    attrs: {
      brand: 'ASUS',
      socket: 'AM5',
      chipset: 'X870E',
      form_factor: 'ATX',
      mem_type: 'DDR5',
      mem_slots: 4,
      m2_slots: 4,
    },
  },
  {
    type: 'mobo',
    title: 'MSI MAG B650 Tomahawk WiFi',
    slug: 'msi-b650-tomahawk',
    price: 849900,
    stock: 16,
    desc: 'Найпопулярніша плата для AM5: потужний VRM, Wi-Fi 6E, 2.5G LAN.',
    attrs: {
      brand: 'MSI',
      socket: 'AM5',
      chipset: 'B650',
      form_factor: 'ATX',
      mem_type: 'DDR5',
      mem_slots: 4,
      m2_slots: 3,
    },
  },
  {
    type: 'mobo',
    title: 'Gigabyte B650I AORUS Ultra',
    slug: 'gigabyte-b650i-aorus',
    price: 979900,
    stock: 8,
    desc: 'Mini-ITX на AM5 для компактних збірок: Wi-Fi 6E, 2 слоти M.2.',
    attrs: {
      brand: 'Gigabyte',
      socket: 'AM5',
      chipset: 'B650',
      form_factor: 'Mini-ITX',
      mem_type: 'DDR5',
      mem_slots: 2,
      m2_slots: 2,
    },
  },
  {
    type: 'mobo',
    title: 'ASRock B550M Pro4',
    slug: 'asrock-b550m-pro4',
    price: 349900,
    stock: 24,
    desc: 'Бюджетна microATX на AM4 з DDR4. Надійна база для збірки на Ryzen 5000.',
    attrs: {
      brand: 'ASRock',
      socket: 'AM4',
      chipset: 'B550',
      form_factor: 'microATX',
      mem_type: 'DDR4',
      mem_slots: 4,
      m2_slots: 2,
    },
  },
  {
    type: 'mobo',
    title: 'MSI MAG B550 Tomahawk',
    slug: 'msi-b550-tomahawk',
    price: 499900,
    stock: 14,
    desc: 'Класика AM4: чудовий VRM, 2.5G LAN, DDR4 до 4400 МГц.',
    attrs: {
      brand: 'MSI',
      socket: 'AM4',
      chipset: 'B550',
      form_factor: 'ATX',
      mem_type: 'DDR4',
      mem_slots: 4,
      m2_slots: 2,
    },
  },
  {
    type: 'mobo',
    title: 'ASUS ROG Maximus Z890 Hero',
    slug: 'asus-z890-hero',
    price: 2299900,
    stock: 5,
    desc: 'Топова плата LGA1851 для Core Ultra: Thunderbolt 4, Wi-Fi 7, 5 слотів M.2.',
    attrs: {
      brand: 'ASUS',
      socket: 'LGA1851',
      chipset: 'Z890',
      form_factor: 'ATX',
      mem_type: 'DDR5',
      mem_slots: 4,
      m2_slots: 5,
    },
  },
  {
    type: 'mobo',
    title: 'MSI PRO B860-P WiFi',
    slug: 'msi-b860-p',
    price: 749900,
    stock: 12,
    desc: 'Плата LGA1851 середнього класу для Core Ultra: DDR5, Wi-Fi 6E.',
    attrs: {
      brand: 'MSI',
      socket: 'LGA1851',
      chipset: 'B860',
      form_factor: 'ATX',
      mem_type: 'DDR5',
      mem_slots: 4,
      m2_slots: 3,
    },
  },
  {
    type: 'mobo',
    title: 'ASUS TUF Gaming Z790-Plus WiFi',
    slug: 'asus-z790-plus',
    price: 899900,
    stock: 11,
    desc: 'LGA1700 з DDR5 і розгоном: витривалий VRM, Wi-Fi 6.',
    attrs: {
      brand: 'ASUS',
      socket: 'LGA1700',
      chipset: 'Z790',
      form_factor: 'ATX',
      mem_type: 'DDR5',
      mem_slots: 4,
      m2_slots: 4,
    },
  },
  {
    type: 'mobo',
    title: 'MSI PRO B760M-P DDR4',
    slug: 'msi-b760m-p-ddr4',
    price: 379900,
    stock: 20,
    desc: 'Доступна microATX на LGA1700 з DDR4 — економія на пам’яті.',
    attrs: {
      brand: 'MSI',
      socket: 'LGA1700',
      chipset: 'B760',
      form_factor: 'microATX',
      mem_type: 'DDR4',
      mem_slots: 4,
      m2_slots: 2,
    },
  },
  {
    type: 'mobo',
    title: 'ASRock B760M-ITX/D4',
    slug: 'asrock-b760m-itx',
    price: 429900,
    stock: 9,
    desc: 'Mini-ITX на LGA1700 з DDR4 для компактної збірки.',
    attrs: {
      brand: 'ASRock',
      socket: 'LGA1700',
      chipset: 'B760',
      form_factor: 'Mini-ITX',
      mem_type: 'DDR4',
      mem_slots: 2,
      m2_slots: 1,
    },
  },

  {
    type: 'case',
    title: 'Lian Li O11 Dynamic EVO',
    slug: 'lianli-o11-dynamic-evo',
    price: 649900,
    stock: 11,
    desc: 'Культовий Mid Tower із подвійним склом. Підтримка кастомного водяного контуру.',
    attrs: {
      brand: 'Lian Li',
      form_factor: 'Mid Tower',
      max_gpu_len: 423,
      fans_included: 0,
      side_panel: 'Загартоване скло',
    },
  },
  {
    type: 'case',
    title: 'NZXT H7 Flow',
    slug: 'nzxt-h7-flow',
    price: 529900,
    stock: 15,
    desc: 'Mid Tower із перфорованою передньою панеллю та чудовим продувом.',
    attrs: {
      brand: 'NZXT',
      form_factor: 'Mid Tower',
      max_gpu_len: 400,
      fans_included: 2,
      side_panel: 'Загартоване скло',
    },
  },
  {
    type: 'case',
    title: 'Fractal Design North',
    slug: 'fractal-north',
    price: 599900,
    stock: 9,
    desc: 'Mid Tower зі скандинавським дизайном і дерев’яною передньою панеллю.',
    attrs: {
      brand: 'Fractal Design',
      form_factor: 'Mid Tower',
      max_gpu_len: 355,
      fans_included: 2,
      side_panel: 'Загартоване скло',
    },
  },
  {
    type: 'case',
    title: 'Fractal Design Meshify 2',
    slug: 'fractal-meshify-2',
    price: 549900,
    stock: 13,
    desc: 'Mid Tower із сітчастою панеллю — максимальний потік повітря.',
    attrs: {
      brand: 'Fractal Design',
      form_factor: 'Mid Tower',
      max_gpu_len: 315,
      fans_included: 3,
      side_panel: 'Сітка',
    },
  },
  {
    type: 'case',
    title: 'Corsair 4000D Airflow',
    slug: 'corsair-4000d-airflow',
    price: 399900,
    stock: 24,
    desc: 'Найпопулярніший Mid Tower: тихий, просторий, з чудовим продувом.',
    attrs: {
      brand: 'Corsair',
      form_factor: 'Mid Tower',
      max_gpu_len: 360,
      fans_included: 2,
      side_panel: 'Загартоване скло',
    },
  },
  {
    type: 'case',
    title: 'Cooler Master HAF 700',
    slug: 'cm-haf-700',
    price: 1399900,
    stock: 4,
    desc: 'Full Tower із п’ятьма вентиляторами та величезним простором для збірки.',
    attrs: {
      brand: 'Cooler Master',
      form_factor: 'Full Tower',
      max_gpu_len: 490,
      fans_included: 5,
      side_panel: 'Загартоване скло',
    },
  },
  {
    type: 'case',
    title: 'Lian Li A4-H2O',
    slug: 'lianli-a4-h2o',
    price: 579900,
    stock: 6,
    desc: 'Mini-ITX об’ємом 11 л — компактна збірка з повнорозмірною відеокартою.',
    attrs: {
      brand: 'Lian Li',
      form_factor: 'Mini-ITX',
      max_gpu_len: 322,
      fans_included: 0,
      side_panel: 'Метал',
    },
  },
  {
    type: 'case',
    title: 'Deepcool CH510',
    slug: 'deepcool-ch510',
    price: 229900,
    stock: 28,
    desc: 'Доступний Mid Tower зі скляною панеллю та зручною прокладкою кабелів.',
    attrs: {
      brand: 'Deepcool',
      form_factor: 'Mid Tower',
      max_gpu_len: 380,
      fans_included: 1,
      side_panel: 'Загартоване скло',
    },
  },
];
