/**
 * Фото комплектуючих — самохостинг у backend/uploads/products.
 * АВТОГЕНЕРовано скриптом scripts/images/gen-maps.ts за вмістом теки. Не редагувати вручну.
 */
export const componentImages: Record<string, string> = {
  'asrock-b550m-pro4': '/uploads/products/asrock-b550m-pro4.jpg',
  'asrock-b760m-itx': '/uploads/products/asrock-b760m-itx.jpg',
  'asus-rog-loki-sfx-850': '/uploads/products/asus-rog-loki-sfx-850.png',
  'asus-x870e-e': '/uploads/products/asus-x870e-e.png',
  'asus-z790-plus': '/uploads/products/asus-z790-plus.jpg',
  'asus-z890-hero': '/uploads/products/asus-z890-hero.jpg',
  'bequiet-pure-power-12m-750': '/uploads/products/bequiet-pure-power-12m-750.jpg',
  'chieftec-polaris-1050': '/uploads/products/chieftec-polaris-1050.jpg',
  'cm-haf-700': '/uploads/products/cm-haf-700.jpg',
  'cm-mwe-bronze-600': '/uploads/products/cm-mwe-bronze-600.jpg',
  'core-i5-13400f': '/uploads/products/core-i5-13400f.jpg',
  'core-i5-14600k': '/uploads/products/core-i5-14600k.png',
  'core-i7-14700k': '/uploads/products/core-i7-14700k.png',
  'core-ultra-7-265k': '/uploads/products/core-ultra-7-265k.png',
  'core-ultra-9-285k': '/uploads/products/core-ultra-9-285k.webp',
  'corsair-4000d-airflow': '/uploads/products/corsair-4000d-airflow.png',
  'corsair-lpx-16-ddr4': '/uploads/products/corsair-lpx-16-ddr4.jpg',
  'corsair-rm1000x': '/uploads/products/corsair-rm1000x.webp',
  'corsair-rm850e': '/uploads/products/corsair-rm850e.webp',
  'corsair-vengeance-32-ddr5': '/uploads/products/corsair-vengeance-32-ddr5.jpg',
  'crucial-pro-64-ddr5': '/uploads/products/crucial-pro-64-ddr5.jpg',
  'deepcool-ch510': '/uploads/products/deepcool-ch510.jpg',
  'deepcool-pk550d': '/uploads/products/deepcool-pk550d.jpg',
  'fractal-meshify-2': '/uploads/products/fractal-meshify-2.jpg',
  'fractal-north': '/uploads/products/fractal-north.jpg',
  'gigabyte-b650i-aorus': '/uploads/products/gigabyte-b650i-aorus.webp',
  'gskill-ripjaws-v-32-ddr4': '/uploads/products/gskill-ripjaws-v-32-ddr4.jpg',
  'gskill-trident-z5-32-ddr5': '/uploads/products/gskill-trident-z5-32-ddr5.jpg',
  'kingston-fury-beast-16-ddr4': '/uploads/products/kingston-fury-beast-16-ddr4.jpg',
  'kingston-fury-beast-32-ddr5': '/uploads/products/kingston-fury-beast-32-ddr5.webp',
  'lianli-a4-h2o': '/uploads/products/lianli-a4-h2o.jpg',
  'lianli-o11-dynamic-evo': '/uploads/products/lianli-o11-dynamic-evo.png',
  'msi-b550-tomahawk': '/uploads/products/msi-b550-tomahawk.jpg',
  'msi-b650-tomahawk': '/uploads/products/msi-b650-tomahawk.jpg',
  'msi-b760m-p-ddr4': '/uploads/products/msi-b760m-p-ddr4.jpg',
  'msi-b860-p': '/uploads/products/msi-b860-p.jpg',
  'msi-mag-a750gl': '/uploads/products/msi-mag-a750gl.jpeg',
  'nzxt-h7-flow': '/uploads/products/nzxt-h7-flow.png',
  'patriot-viper-venom-16-ddr5': '/uploads/products/patriot-viper-venom-16-ddr5.jpg',
  'ryzen-5-5600': '/uploads/products/ryzen-5-5600.jpg',
  'ryzen-5-7600': '/uploads/products/ryzen-5-7600.jpg',
  'ryzen-7-7800x3d': '/uploads/products/ryzen-7-7800x3d.jpg',
  'ryzen-7-9800x3d': '/uploads/products/ryzen-7-9800x3d.png',
  'ryzen-9-9950x': '/uploads/products/ryzen-9-9950x.jpg',
  'seasonic-focus-gx-650': '/uploads/products/seasonic-focus-gx-650.jpg',
  'seasonic-prime-tx-1000': '/uploads/products/seasonic-prime-tx-1000.jpg',
};
